config/routes.rb
Rails.application.routes.draw do

  get 'diners/api', :to => 'diners#index'
  get '/api/diners', :to => 'diners#display_api'
  get '/api/deals', :to => 'deals#display_api'

  resources :diners do
     resources :deals, only: [:new, :create]
  end

 
  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :diner
end

app/models/diner.rb
class Diner < ActiveRecord::Base
    has_secure_password
    has_many :deals
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

protected

    def current_user
        @current_user ||= Diner.find(session[:diner_id]) if session[:diner_id]
    end

    helper_method :current_user
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

    def new
        @diner = Diner.find(params[:diner_id])
        @deal = @diner.deals.build
    end

    def display_api
        @deals = Deal.all
        render json: @deals
    end



    def create
        @diner = Diner.find(params[:diner_id])
        @deal = @diner.deals.build(deal_params) # @deal.user_id = current_user.id

        if @deal.save
            redirect_to diners_path, notice: "Review created successfully"
            # redirect_to @diner, notice: "Review created successfully"
        else
            render :new
        end
    end

    protected

    def deal_params
        params.require(:deal).permit(:name, :old_price, :new_price, :offer_start, :offer_end, :pickup_start, :pickup_end, :description)
    end

end

app/controllers/diners_controller.rb
class DinersController < ApplicationController

  def new
    @diner = Diner.new
  end

  def index
    @diners = Diner.all
  end

  def display_api
    @diners = Diner.all
    # @messages = current_user.messages
    render json: @diners
  end

  def create
    @diner = Diner.new(diner_params)

    if @diner.save
      session[:diner_id] = @diner.id
      redirect_to diners_path, notice: "Welcome aboard, #{@diner.email}!"
    else
      render :new
    end
  end

  protected

  def diner_params
    params.require(:diner).permit(:email, :name, :password, :password_confirmation, :location, :description, :rating)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController



    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)

        if @restaurant.save
            redirect_to restaurants_path
        else
            render :new
        end
    end

    def update
        @restaurant = Restaurant.find(params[:id])

        if @restaurant.update_attributes(restaurant_params)
            redirect_to restaurant_path(@restaurant)
        else
            render :edit
        end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
        redirect_to restaurants_path
    end

    protected

    def restaurant_params
        params.require(:restaurant).permit(
            :name, :location, :rating, :description
            )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        diner = Diner.find_by(email: params[:email])

        if diner && diner.authenticate(params[:password])
            session[:diner_id] = diner.id
            redirect_to diners_path, notice: "Welcome back, #{diner.name}!"
        else
            flash.now[:alert] = "Log in failed..."
            render :new
        end
    end

    def destroy
      session[:diner_id] = nil
      redirect_to diners_path, notice: "Adios!"
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/diners_helper.rb
module DinersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deals/create.html.erb
<h1>Deals#create</h1>
<p>Find me in app/views/deals/create.html.erb</p>

app/views/deals/new.html.erb
<h1>Deals#new</h1>
<p>Find me in app/views/deals/new.html.erb</p>

<!-- <%= link_to "Back to diner", diner_path(@diner) %><br/> -->

<h2>Write a deal for <em><%= @diner.name %></em>.</h2>

<%= form_for([@diner, @deal]) do |f| %>
<% if @deal.errors.any? %>
<div>
  <%= pluralize(@deal.errors.count, "error") %> prevented the deal from being saved:
  <ul>
    <% @deal.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
</div>
<% end %>

<div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</div>
<div>
    <%= f.label :old_price %><br>
    <%= f.number_field :old_price %>
</div>
<div>
    <%= f.label :new_price %><br>
    <%= f.number_field :new_price %>
</div>

<div>
<%= f.label :offer_start %><br>
<%= f.date_field :offer_start %>
</div>

<div>
<%= f.label :offer_end %><br>
<%= f.date_field :offer_end %>
</div>

<div>
<%= f.label :pickup_start %><br>
<%= f.date_field :pickup_start %>
</div>

<div>
<%= f.label :pickup_end %><br>
<%= f.date_field :pickup_end %>
</div>

<div>
    <%= f.label :description %><br>
    <%= f.text_area "description" %>
</div>

<div><%= f.submit "Submit" %></div>
<% end %>

app/views/diners/create.html.erb
<h1>Diners#create</h1>
<p>Find me in app/views/diners/create.html.erb</p>

app/views/diners/index.html.erb
<!-- <h1>Diners#index</h1> -->
<!-- <p>Find me in app/views/diners/index.html.erb</p> -->


<h1> Cheep Eats Restaurant Admin Panel </h1>

<!-- <div><%= link_to "Make a new account for your diner!", new_diner_path %></div> -->

<% if current_user %>
<div><%= link_to "Create deal!", new_diner_deal_path(current_user) %></div> 
<% end %>

</br>


<% if current_user == nil %>
<div>You are not logged in.</div>



<% else %>

<div>Your diner info:</div>

    <% @diners.each do |diner| %>
        <% if current_user.id == diner.id %>
            <div>email: <%= diner.email %></div>
            <div>name: <%= diner.name %></div>
            <div>location: <%= diner.location %></div>
            <div>description: <%= diner.description %></div>
            <div>rating: <%= diner.rating %></div>
            <div>
            description: <%= diner.description %>
            </div>
            </br>
            <div>Deals offered: </div>
            <% diner.deals.each do |deal| %>
            <div>name: <%= deal.name %></div>
            <div>old_price: <%= deal.old_price %></div>
            <div>new_price: <%= deal.new_price %></div>
            <div>offer_start: <%= deal.offer_start %></div>
            <div>offer_end: <%= deal.offer_end %></div>
            <div>pickup_start: <%= deal.pickup_start %></div>
            <div>pickup_end: <%= deal.pickup_end %></div>
            <div>description: <%= deal.description %></div>
            </br>
        <% end %>
    <% end %>
<% end %>





<% end %>  

app/views/diners/new.html.erb
<h1>Diners#new</h1>
<p>Find me in app/views/diners/new.html.erb</p>


<h1>Sign Up</h1>
    <%= form_for @diner do |f| %>
      <% if @diner.errors.any? %>
        <div>
          <%= pluralize(@diner.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @diner.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <%= f.label :location %><br>
        <%= f.text_field :location %>
      </div>
      <div>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div>
        <%= f.label :rating %><br>
        <%= f.text_field :rating %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
    Signed in as <%= current_user.name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
    <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_diner_path %>
    <% end %>
</small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <% flash.each do |key, value| %>
   <%= content_tag(:div, value) %>
   <% end %>
   <%= yield %>
   <%= render 'layouts/footer' %>


<<<<<<< HEAD
<%= yield %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://s.cdpn.io/17920/jquery.easing.1.3.js"></script>
<script src="http://s.cdpn.io/17920/jquery.animate-enhanced.min.js"></script>
<script src="http://s.cdpn.io/17920/hammer.min.js"></script>
<script src="http://s.cdpn.io/17920/jquery.superslides.js" type="text/javascript" charset="utf-8"></script>
=======
>>>>>>> 592a483bad4b76387a753ede59c9988b9d630fb7

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>

</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>


<h1>Rotten Mangoes</h1>
<%= link_to "Submit a restaurant!", new_restaurant_path %>
<hr>
<% @restaurants.each do |restaurant| %>

<h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>

<p><%= restaurant.description %></p>
<hr>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>


<%= link_to "Back to all restaurants", restaurants_path %>

<h2>Submit a restaurant!</h2>
<%= form_for @restaurant do |f| %>
<div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</div>


<div>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
</div>
<div>
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
</div>

<div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.submit "Submit" %> 
</div>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>



<%= link_to "Back to all restaurants", restaurants_path %><br/>


<h2><%= @restaurant.name %> (<%= link_to "edit", edit_restaurant_path(@restaurant) %>, <%= link_to "delete", restaurant_path(@restaurant), method: :delete, confirm: "You sure?" %>)</h2>

<p><%= @restaurant.description %></p>

app/views/welcome/index.html.erb
  <div id="slides">
    <ul class="slides-container">
    	<li><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/17920/dumbo.jpg" width="1680" height="1050">
        	<div class="caption-wrapper">
            	<div class="caption">
            		<h1>Headlines are awesome!</h1>
  <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            	</div>
   			</div>
        </li>
    	<li><img src="http://s.cdpn.io/17920/guitar-close_1.jpg" width="2000" height="1333">
        	<div class="caption-wrapper">
            	<div class="caption">
            		<h1>This is a headline</h1>
  <p>Suspendisse elementum  iaculis blandit. Nunc eget fringilla metus, sit amet aliquet urna.</p>
            	</div>
   			</div>
        </li>
    </ul>

    <nav class="slides-navigation">
      <a href="#" class="next">Next</a>
      <a href="#" class="prev">Previous</a>
    </nav>

   <a href="#page"><img src="http://s.cdpn.io/17920/button-down.png" width="175" height="77" id="button-down"></a>

    <div id="primary-nav"><%= link_to "Sign Up", new_diner_path %> | About Us | Contact | Login</div>
  </div>

<div id="page">
  <h2>Heading 2</h2>
  <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam laoreet  commodo magna, id dictum dolor lacinia sed. Cras in dolor ultricies,  tempus elit eget, tincidunt nibh. Nunc lobortis commodo nisl et  tristique. Mauris lacinia elit vitae mauris volutpat molestie. Aliquam  at arcu nec diam pulvinar blandit quis eu augue. Suspendisse elementum  iaculis blandit. Nunc eget fringilla metus, sit amet aliquet urna. Sed  sodales lectus tellus, a condimentum orci facilisis at. </p>
  <p>Suspendisse  cursus purus at sodales pellentesque. Sed vel sapien pulvinar, tempus  leo et, consequat risus. Donec eu gravida justo. Nulla ut mi posuere,  fringilla augue sed, tempus sem. Pellentesque tincidunt dignissim lacus. Nunc commodo ante vel neque blandit, sed varius orci placerat. Lorem  ipsum dolor sit amet, consectetur adipiscing elit. Etiam et diam sit  amet risus congue euismod a tempus magna. Vivamus sed nunc dapibus,  fermentum lectus et, blandit urna. </p>
  <p>Donec ornare adipiscing placerat.  Vestibulum congue pretium dolor sed tincidunt. Class aptent taciti  sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.  Praesent augue nibh, placerat nec arcu quis, tempor dictum lacus. In  lacinia dolor sed nunc venenatis faucibus. Praesent bibendum dolor eros,  a porttitor risus elementum vitae. Praesent lobortis elit ut lectus  aliquam accumsan. Cras volutpat felis odio, ac dictum elit pretium eget.  Proin ut diam in tortor imperdiet venenatis. Mauris laoreet suscipit  facilisis. </p>
  </div>


 <script>
    $(function() {
      var $slides = $('#slides');

      Hammer($slides[0]).on("swipeleft", function(e) {
        $slides.data('superslides').animate('next');
      });

      Hammer($slides[0]).on("swiperight", function(e) {
        $slides.data('superslides').animate('prev');
      });

      $slides.superslides({
        hashchange: true,
        play: 4000
      });

      $('#slides').on('mouseenter', function() {
        $(this).superslides('stop');
        console.log('Stopped')
      });
      $('#slides').on('mouseleave', function() {
        $(this).superslides('start');
        console.log('Started')
      });

    });

  </script>